version: '3.2'

networks:
  microservices-pattern_default:
    external: true

services:
  customer:
    build:
      context: .
      dockerfile: ./services/customer/Dockerfile
      target: builder
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=${GOOGLE_APPLICATION_CREDENTIALS}
    command: >
      ash -c
      "GO111MODULE=off go get github.com/cespare/reflex &&
      reflex -c /work/reflex.conf"
    ports:
      - "127.0.0.1:50051:8080"
    volumes:
      - "./services/customer/reflex.conf:/work/reflex.conf"
      - ".:/work"
      - "${GOOGLE_APPLICATION_CREDENTIALS}:${GOOGLE_APPLICATION_CREDENTIALS}"
    container_name: customer_service
    networks:
      - microservices-pattern_default
  gateway:
    build:
      context: .
      dockerfile: ./services/gateway/Dockerfile
      target: builder
    environment:
      - CATALOG_SERVICE_ADDR=catalog_service:8080
      - GOOGLE_APPLICATION_CREDENTIALS=${GOOGLE_APPLICATION_CREDENTIALS}
    command: >
      ash -c
      "GO111MODULE=off go get github.com/cespare/reflex &&
      reflex -c /work/reflex.conf"
    ports:
      - "127.0.0.1:50053:8080"
    volumes:
      - "./services/gateway/reflex.conf:/work/reflex.conf"
      - ".:/work"
      - "${GOOGLE_APPLICATION_CREDENTIALS}:${GOOGLE_APPLICATION_CREDENTIALS}"
    container_name: gateway_service
    networks:
      - microservices-pattern_default
  catalog:
    build:
      context: .
      dockerfile: ./services/catalog/Dockerfile
      target: builder
    environment:
      - ITEM_SERVICE_ADDR=item_service:8080
      - CUSTOMER_SERVICE_ADDR=customer_service:8080
      - GOOGLE_APPLICATION_CREDENTIALS=${GOOGLE_APPLICATION_CREDENTIALS}
    command: >
      ash -c
      "GO111MODULE=off go get github.com/cespare/reflex &&
      reflex -c /work/reflex.conf"
    ports:
      - "127.0.0.1:50054:8080"
    volumes:
      - "./services/catalog/reflex.conf:/work/reflex.conf"
      - ".:/work"
      - "${GOOGLE_APPLICATION_CREDENTIALS}:${GOOGLE_APPLICATION_CREDENTIALS}"
    container_name: catalog_service
    networks:
      - microservices-pattern_default
  item:
    build:
      context: .
      dockerfile: ./services/item/Dockerfile
      target: builder
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=${GOOGLE_APPLICATION_CREDENTIALS}
    command: >
      ash -c
      "GO111MODULE=off go get github.com/cespare/reflex &&
      reflex -c /work/reflex.conf"
    ports:
      - "127.0.0.1:50055:8080"
    volumes:
      - "./services/item/reflex.conf:/work/reflex.conf"
      - ".:/work"
      - "${GOOGLE_APPLICATION_CREDENTIALS}:${GOOGLE_APPLICATION_CREDENTIALS}"
    container_name: item_service
    networks:
      - microservices-pattern_default
