name: "catalog service Pull Request Check"

on:
  push:
    paths:
      - "services/catalog/**"
      - ".github/workflows/catalog-service-pull-request.yaml"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: '^1.17' # The Go version to download (if necessary) and use.\
      - name: Check out code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          go mod download
      - name: Build
        run: go build ./services/catalog/...
      - name: Test
        run: go test ./services/catalog/... -v
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.29
          working-directory: services/catalog
