name: gateway

on:
  push:
    paths:
      - "services/gateway/**"
      - ".github/workflows/gateway-service-pull-request.yaml"
  pull_request:
    types: [opened, synchronize]
    paths:
      - "services/gateway/**"

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: setup go
        uses: actions/setup-go@v2
        with:
          go-version: '1.17.6' # The Go version to download (if necessary) and use.\
        id: go
      - name: check out
        uses: actions/checkout@v2
  build:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: build
        run: go build ./services/gateway/...
  test:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: test
        run: go test ./services/gateway/... -v
  lint:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.29
          working-directory: services/gateway
