name: gateway

on:
  push:
    paths:
      - "services/gateway/**"
      - ".github/workflows/gateway-service-pull-request.yaml"
  pull_request:
    types: [opened, synchronize]
    paths:
      - "services/gateway/**"

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: '^1.17' # The Go version to download (if necessary) and use.\
        id: go
      - name: Check out code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          go mod download
      # - name: Build
      #   run: go build ./services/gateway/...
      - name: Test
        run: go test ./services/gateway/... -v
  build:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: go build ./services/gateway/...
  # test:
  #   needs: setup
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  lint:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.29
          working-directory: services/gateway
